# Generated by Django 3.1.2 on 2020-10-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='DateTimeField',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='DateTimeField',
            new_name='datetime',
        ),
    ]
